### ISSUE TITLE
Server setup for Android App

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/ZapServer#1]
- [x] Add basic user registration function API

- [x] Migrate from SQlite3 to PostgreSQL

- [x] Host on Heroku

- [x] RESTful with Android side

- [x] Token authentication ability

- [x] Email token

- [x] Magic Link Login

**Comment by DevArenaCN** [comment]
Having issues with RVM on my laptop. Cleaning up and reinstall the whole environment as we speak. Might take some time...

**Comment by KaustubhG** [comment]
Okay. No worries.

**Comment by DevArenaCN** [comment]
@KaustubhG @thegreyd you guys can setup the app with local db authentication first while I get the server up and ready.

**Comment by DevArenaCN** [comment]
Rails environment is ready on my laptop, but it's harder than I thought it would be, devise no longer support token_auth so I have to take it to another direction.

**Comment by DevArenaCN** [comment]
Still having the Ruby version issue on my OS. Still trying to figure things out, if I can't get things going by tonight, I'll switch to another approach to setup the server (A.K.A  ditching Ruby on Rails)

**Comment by DevArenaCN** [comment]
Slowly moving forward for the day, I have API calls for login and logout, still trying to get the token auth to work before I move to register...Hopefully I can get it done before Sunday.

**Comment by DevArenaCN** [comment]
Curl used for login 
`curl -k -v -H "Content-Type:application/json" -X POST -d '{"session":{"password":"12345678","email":"example@zapserver.com"}}' https://zapserver.herokuapp.com/api/sessions/`

**Comment by DevArenaCN** [comment]
Headers you need:
<img width="1245" alt="screen shot 2017-02-12 at 1 22 59 pm" src="https://cloud.githubusercontent.com/assets/4381690/22864854/e2d91c90-f126-11e6-9039-bbaf8de3a6ed.png">

Content and the web address you need to send the JSON to:
<img width="1253" alt="screen shot 2017-02-12 at 1 23 02 pm" src="https://cloud.githubusercontent.com/assets/4381690/22864858/f687f270-f126-11e6-809e-1d8ff77f32bf.png">

**Comment by DevArenaCN** [comment]
Logout format:

`curl -k -v -H "Content-Type:application/json" -X DELETE https://zapserver.herokuapp.com/api/sessions/DxsBFrATCNxt_9J8f94a`    

for the part where DxsBFrATCNxt_9J8f94a change it to user's auth_token

**Comment by DevArenaCN** [comment]
Server side register, login and logout APIs have been implemented and tested. Working on magic link implementation next week.

**Comment by DevArenaCN** [comment]
Done. Adding the documentations now
