### ISSUE TITLE
Email verification design discussion.

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/ZapServer#13]
The email verification step now takes place at the beginning. I was thinking this may not be the ideal choice, because we only need it for the magic link setup, and it increases steps to register(which we are trying to reduce). Actually we can design, so username can be anything not only email - an alias that you use, like Reddit. Reddit only asks for email after registration when it needs to connect with you, ex-when resetting password. 

In either case, the email verification step can be in magic link setup, linked to a button to verify email. If we accept email as username, we'll send to that address; if we accept usernames of any kind, we'll have a field asking for email, and send to that. 

I maybe overlooking somethings. Do share your thoughts.

**Comment by DevArenaCN** [comment]
I'm doing the user register/authentication using devise, and email verification comes with that. The idea is great, but if we went with that, I'll have to start the whole process, including auth_token all from the scratch, I don't think we have the time for that. Let's finish testing first, I'll see what I can do, but I really doubt that I can get that done in time.

**Comment by thegreyd** [comment]
Okay. I thought we could rollback to what we previously had. But yeah if it's too much trouble, the system we have now is fine.

**Comment by KaustubhG** [comment]
I guess the email verification is fine as the very first step too. Since our user-name **is** the user's email, the verification part makes sure that the user uses a valid email address to sign-up! 😄

**Comment by DevArenaCN** [comment]
Or we can call this a trade off, for having three method of authentication you need to use email for your username and verify your email address.

**Comment by thegreyd** [comment]
Yes good point.
