### ISSUE TITLE
Magic link api call quotes error

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/ZapServer#14]
When I make the following call, it returns a bad request:
- Call: `curl -k -v -H "Content-Type:application/json" -X POST -d "{'magiclink':{'email':'sid.sharma0@gmail.com'}}" https://zapserver.herokuapp.com/api/magiclinks/
`
- Response: `{"status":400,"error":"Bad Request"}`

Instead when you make this call it accepts
- `curl -k -v -H "Content-Type:application/json" -X POST -d '{"magiclink":{"email":"sid.sharma0@gmail.com"}}' https://zapserver.herokuapp.com/api/magiclinks/`

- Response: 204

The difference between them is in the JSON body, I inter-changed single and double quotes. I am not able to implement the single quotes version in Java, because strings can't be inside single quotes. 
Please fix this.

**Comment by DevArenaCN** [comment]
@thegreyd The reason it throws an error is because single quote is not a legal JSON format, you need to use double quotes instead. There's nothing I can do on the server side since there's a strict policy regarding JSON format.

**Comment by thegreyd** [comment]
even this doesn't work
`curl -k -v -H "Content-Type:application/json" -X POST -d "{"magiclink":{"email":"sid.sharma0@gmail.com"}}" https://zapserver.herokuapp.com/api/magiclinks/`

this used to work in the login request.

**Comment by thegreyd** [comment]
Here's what I am doing for login request:
`json_request = String.format("{ \"session\": { \"email\": \"%s\", \"password\": \"%s\" } }",email, passwd);`

Here's the magic link json
`json_request = String.format("{ \"magiclink\": { \"email\": \"%s\" } }",email);
`

**Comment by thegreyd** [comment]
Got it. An error in the url.

**Comment by DevArenaCN** [comment]
Cool. I'm making a change to the return JSON since now it returns nothing after sending the magic link email

**Comment by DevArenaCN** [comment]
Done. Now it will return a JSON: {"Message":"Magic Link Sent"} if the email is sent out successfully.
